using System;

class Program
{
    static void Main()
    {
		var nums = new[] {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, };
		Console.WriteLine(string.Join(", ", nums));
		Console.WriteLine("The numbers in the array were generated by T4 template!");
    }
}