CREATE SCHEMA IF NOT EXISTS `Library`;
USE `Library` ;

CREATE TABLE IF NOT EXISTS `Library`.`Books` (
  `BookID` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(100) NOT NULL,
  `Author` VARCHAR(45) NOT NULL,
  `PublishDate` DATETIME NULL,
  `ISBN` CHAR(13) NULL,
  PRIMARY KEY (`BookID`))
ENGINE = InnoDB;