//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoChat.Client {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Connections : global::System.Configuration.ApplicationSettingsBase {
        
        private static Connections defaultInstance = ((Connections)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Connections())));
        
        public static Connections Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mongodb://telerik:chat@ds035300.mongolab.com:35300/mongochat")]
        public string MongoCloud {
            get {
                return ((string)(this["MongoCloud"]));
            }
            set {
                this["MongoCloud"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mongodb://localhost")]
        public string MongoLocal {
            get {
                return ((string)(this["MongoLocal"]));
            }
            set {
                this["MongoLocal"] = value;
            }
        }
    }
}
