//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateTimeConverter.Client.DateTimeConverterServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DateTimeConverterServices.IDateTimeConverter")]
    public interface IDateTimeConverter {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDateTimeConverter/GetDayOfWeek", ReplyAction="http://tempuri.org/IDateTimeConverter/GetDayOfWeekResponse")]
        string GetDayOfWeek(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDateTimeConverter/GetDayOfWeek", ReplyAction="http://tempuri.org/IDateTimeConverter/GetDayOfWeekResponse")]
        System.Threading.Tasks.Task<string> GetDayOfWeekAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDateTimeConverterChannel : DateTimeConverter.Client.DateTimeConverterServices.IDateTimeConverter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DateTimeConverterClient : System.ServiceModel.ClientBase<DateTimeConverter.Client.DateTimeConverterServices.IDateTimeConverter>, DateTimeConverter.Client.DateTimeConverterServices.IDateTimeConverter {
        
        public DateTimeConverterClient() {
        }
        
        public DateTimeConverterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DateTimeConverterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DateTimeConverterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DateTimeConverterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDayOfWeek(System.DateTime date) {
            return base.Channel.GetDayOfWeek(date);
        }
        
        public System.Threading.Tasks.Task<string> GetDayOfWeekAsync(System.DateTime date) {
            return base.Channel.GetDayOfWeekAsync(date);
        }
    }
}
